### ISSUE TITLE
Fix Can't find variable: UIFontMetrics

### ISSUE THREAD

**Issue by msaravitz** [darkmantle/nativescript-font-scale#10]
Application crashes for users pre iOS 11, the error in my crashlytics is: Can't find variable: UIFontMetrics. I noticed [here](https://developer.apple.com/documentation/uikit/uifontmetrics) that the minimum iOS version for UIFontMetrics is iOS 11. Perhaps a simple OS version check before using the UIFontMetrics? Thanks

**Comment by darkmantle** [comment]
@msaravitz Thank you for your report! I created this library out of a need for something in my own project so it is slightly limited right now. I'll try and fix this issue sometime this week, time depending.

**Comment by darkmantle** [comment]
Update published
